name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: adityak74/huggingface-sync-action@v0.5.0
        with:
          github_repo_id: jacksonsantosjr/atualizacao-cadastral
          huggingface_repo_id: jacksonsantosjr/atualizacao-de-cadastro
          repo_type: space
          huggingface_token: ${{ secrets.HF_TOKEN }}
